version: '1'
services:
  docker-backend:
    container_name: detecto-backend
    build:
      context: .
      dockerfile: Dockerfile
    image: detecto/backend:latest
    ports:
      - 8080:8080
    #networks:
    #  - spring-cloud-network
#networks:
#  spring-cloud-network:
#    driver: bridge